<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/18 14:12:43
sfConfig::add(array(
  'mod_sfcooperationarticle_enabled' => true,
  'mod_sfcooperationarticle_view_class' => 'sfPHP',
));
