<?php
// auto-generated by sfViewConfigHandler
// date: 2018/03/18 14:12:43
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('articles.css', '', array ());
  $response->addStylesheet('article.css', '', array ());
  $response->addStylesheet('base.min.css', '', array ());
  $response->addStylesheet('fontsIco.min.css', '', array ());
  $response->addStylesheet('bannerAnimation.min.css', '', array ());
  $response->addStylesheet('1027_3.min.css', '', array ());
  $response->addStylesheet('cubeNavigation.min.css', '', array ());
  $response->addStylesheet('font-awesome.min.css', '', array ());
  $response->addJavascript('2052.js', '', array ());
  $response->addJavascript('jqmobi.min.js', '', array ());
  $response->addJavascript('jqmobi_ui.min.js', '', array ());
  $response->addJavascript('mobi.min.js', '', array ());


