<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/18 02:45:29
sfConfig::add(array(
  'mod_sfcooperationmobile_enabled' => true,
  'mod_sfcooperationmobile_view_class' => 'sfPHP',
));
