cooperation_affiliate:
  class: sfDoctrineRouteCollection
  options:
    model:                CooperationAffiliate
    module:               affiliate
    prefix_path:          /affiliate
    column:               id
    with_wildcard_routes: true

cooperation_notice_autoNotice:
  class: sfDoctrineRouteCollection
  options:
    model:                CooperationNotice
    module:               autoNotice
    prefix_path:          /autoNotice
    column:               id
    with_wildcard_routes: true

cooperation_category:
  class: sfDoctrineRouteCollection
  options:
    model:                CooperationCategory
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

cooperation_notice:
  class: sfDoctrineRouteCollection
  options:
    model:                CooperationNotice
    module:               notice
    prefix_path:          notice
    column:               id
    with_wildcard_routes: true

cooperation_article:
  class: sfDoctrineRouteCollection
  options:
    model:                CooperationArticle
    module:               article
    prefix_path:          article
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: notice, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
