<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/18 02:40:33
sfConfig::add(array(
  'mod_sfcooperationmain_enabled' => true,
  'mod_sfcooperationmain_view_class' => 'sfPHP',
));
