<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CooperationCategoryAffiliate', 'doctrine');

/**
 * BaseCooperationCategoryAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $affiliate_id
 * @property CooperationAffiliate $CooperationAffiliate
 * @property CooperationCategory $CooperationCategory
 * 
 * @method integer                      getCategoryId()           Returns the current record's "category_id" value
 * @method integer                      getAffiliateId()          Returns the current record's "affiliate_id" value
 * @method CooperationAffiliate         getCooperationAffiliate() Returns the current record's "CooperationAffiliate" value
 * @method CooperationCategory          getCooperationCategory()  Returns the current record's "CooperationCategory" value
 * @method CooperationCategoryAffiliate setCategoryId()           Sets the current record's "category_id" value
 * @method CooperationCategoryAffiliate setAffiliateId()          Sets the current record's "affiliate_id" value
 * @method CooperationCategoryAffiliate setCooperationAffiliate() Sets the current record's "CooperationAffiliate" value
 * @method CooperationCategoryAffiliate setCooperationCategory()  Sets the current record's "CooperationCategory" value
 * 
 * @package    cooperation
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCooperationCategoryAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cooperation_category_affiliate');
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('affiliate_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CooperationAffiliate', array(
             'local' => 'affiliate_id',
             'foreign' => 'id'));

        $this->hasOne('CooperationCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));
    }
}