<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CooperationCategory', 'doctrine');

/**
 * BaseCooperationCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $CooperationCategoryAffiliate
 * @property Doctrine_Collection $CooperationNotice
 * @property Doctrine_Collection $CooperationArticle
 * 
 * @method integer             getId()                           Returns the current record's "id" value
 * @method string              getName()                         Returns the current record's "name" value
 * @method timestamp           getCreatedAt()                    Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()                    Returns the current record's "updated_at" value
 * @method Doctrine_Collection getCooperationCategoryAffiliate() Returns the current record's "CooperationCategoryAffiliate" collection
 * @method Doctrine_Collection getCooperationNotice()            Returns the current record's "CooperationNotice" collection
 * @method Doctrine_Collection getCooperationArticle()           Returns the current record's "CooperationArticle" collection
 * @method CooperationCategory setId()                           Sets the current record's "id" value
 * @method CooperationCategory setName()                         Sets the current record's "name" value
 * @method CooperationCategory setCreatedAt()                    Sets the current record's "created_at" value
 * @method CooperationCategory setUpdatedAt()                    Sets the current record's "updated_at" value
 * @method CooperationCategory setCooperationCategoryAffiliate() Sets the current record's "CooperationCategoryAffiliate" collection
 * @method CooperationCategory setCooperationNotice()            Sets the current record's "CooperationNotice" collection
 * @method CooperationCategory setCooperationArticle()           Sets the current record's "CooperationArticle" collection
 * 
 * @package    cooperation
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCooperationCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cooperation_category');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CooperationCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('CooperationNotice', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('CooperationArticle', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}