<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/22 22:34:15
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_sf_guard_plugin_algorithm_callable' => array (
  0 => 'MyCryptoClass',
  1 => 'MyCryptoMethod',
),
  'app_sf_guard_plugin_remember_key_expiration_age' => 2592000,
  'app_sf_guard_plugin_remember_cookie_name' => 'myAppRememberMe',
  'app_sf_guard_plugin_allow_login_with_email' => true,
));
