<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/03/22 22:34:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cooperation',
  'username' => 'root',
  'password' => '123456',
  'name' => 'doctrine',
)),);
