<?php

/**
 * PluginCooperationCategoryAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCooperationCategoryAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCooperationCategoryAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCooperationCategoryAffiliate');
    }
}