<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/04/24 23:25:16
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_notices_on_homepage' => 10,
  'app_max_notices_on_category' => 20,
  'app_max_articles_on_homepage' => 3,
  'app_max_articles_on_category' => 20,
));
