<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/04/24 23:25:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cooperation',
  'username' => 'root',
  'password' => '5E92c33bdd42',
  'name' => 'doctrine',
)),);
