<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/04/24 23:25:16
sfConfig::add(array(
  'mod_sfcooperationmobile_enabled' => true,
  'mod_sfcooperationmobile_view_class' => 'sfPHP',
));
