<?php

/**
 * CooperationCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CooperationCategoryTable extends PluginCooperationCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CooperationCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CooperationCategory');
    }
}