<?php

/**
 * CooperationNoticeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CooperationNoticeTable extends PluginCooperationNoticeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CooperationNoticeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CooperationNotice');
    }
}