<?php

/**
 * CooperationCategoryAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CooperationCategoryAffiliateTable extends PluginCooperationCategoryAffiliateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CooperationCategoryAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CooperationCategoryAffiliate');
    }
}