<?php

/**
 * CooperationAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CooperationAffiliateTable extends PluginCooperationAffiliateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CooperationAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CooperationAffiliate');
    }
}