<?php

/**
 * CooperationArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CooperationArticleTable extends PluginCooperationArticleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CooperationArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CooperationArticle');
    }
}