<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/18 02:37:33
sfConfig::add(array(
  'mod_sfcooperationnotice_enabled' => true,
  'mod_sfcooperationnotice_view_class' => 'sfPHP',
));
