# apps/frontend/config/routing.yml
localized_homepage:
  url:   /:sf_culture/
  param: { module: sfCooperationMobile, action: index }
  requirements:
    sf_culture: (?:fr|en)
 
homepage:
  url:   /
  param: { module: sfCooperationMobile, action: index }